set nocompatible
filetype off

source $HOME/.vim/packages.vim

set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile                    " It's 2012, Vim."
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set t_Co=256
syntax on

set spelllang=en
set spellfile=$HOME/.vim/spell/en.utf-8.add

" Fix backspace
set backspace=indent,eol,start
" fixdel " neovim incompatible

" Send more characters for redraws
set ttyfast

" Use Bash as shell
set shell=/usr/local/bin/bash

" Enable mouse use in all modes
set mouse=a
" set ttymouse=xterm2 " neovim incompatible

filetype plugin indent on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

" Display extra whitespace
set list listchars=tab:  ,trail:·
" set list listchars=tab:»·,trail:·
" Clipboard fix for OsX
set clipboard=unnamed

" Numbers
set number
set numberwidth=2

"Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b,u,t

" When spellcheck is enabled, autocomplete from dictionary
set complete+=kspell

" Exhuberant Ctags
let Tlist_Ctags_Cmd = "/usr/bin/env ctags -R --exclude=.git --exclude=log -f ./.tags *"
set tags+=.tags

source $HOME/.vim/coc.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/rails.vim
source $HOME/.vim/snippets.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/testing.vim
source $HOME/.vim/tmux.vim
source $HOME/.vim/visual_fixes.vim
source $HOME/.vim/extras.vim
source $HOME/.vim/markdown.vim
source $HOME/.vim/dash.vim
source $HOME/.vim/python.vim
source $HOME/.vim/go.vim
source $HOME/.vim/work.vim

packloadall
