set nocompatible
filetype off

" Initialize minpac for plugin management
set packpath^=~/.vim
packadd minpac
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()

call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})

if has('nvim')
  call minpac#add('kassio/neoterm')
  call minpac#add('Shougo/deoplete.nvim')
  call minpac#add('fishbullet/deoplete-ruby', { 'type': 'opt' })
endif

"call minpac#add('SirVer/ultisnips', { 'type': 'opt' })
"call minpac#add('benmills/vimux', { 'type': 'opt' })
"call minpac#add('cloud8421/vimux-cucumber', { 'type': 'opt' })
"call minpac#add('davidoc/taskpaper.vim', { 'type': 'opt' })
"call minpac#add('jgdavey/vim-turbux', { 'type': 'opt' })
"call minpac#add('mattn/emmet-vim', { 'type': 'opt' })
"call minpac#add('pgr0ss/vimux-ruby-test', { 'type': 'opt' })
"call minpac#add('tomasr/molokai', { 'type': 'opt' })
call minpac#add('AndrewRadev/splitjoin.vim')                            " convert between single-line and multi-line blocks
call minpac#add('KurtPreston/vim-autoformat-rails', { 'type': 'opt' })
call minpac#add('aperezdc/vim-template', { 'type': 'opt' })
call minpac#add('chrisbra/csv.vim')
call minpac#add('cloud8421/vim-neatstatus')                             " Add a nice status display
call minpac#add('craigemery/vim-autotag')
call minpac#add('easymotion/vim-easymotion')                            " Makes it easy to jump around in files
call minpac#add('elixir-lang/vim-elixir')
call minpac#add('fatih/vim-go')
call minpac#add('godlygeek/tabular', { 'type': 'opt' })
call minpac#add('honza/vim-snippets', { 'type': 'opt' })
call minpac#add('jeetsukumaran/vim-buffergator')                        " Make buffer navigation more graphical
call minpac#add('junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }) " Fuzzy file finder
call minpac#add('junegunn/vim-easy-align', { 'type': 'opt' })
call minpac#add('kana/vim-textobj-user') " required for nelstrom/vim-textobj-rubyblock
call minpac#add('kchmck/vim-coffee-script')
call minpac#add('mattn/gist-vim', { 'type': 'opt' })
call minpac#add('mhinz/vim-signify') " show source control diffs in a column
call minpac#add('nelstrom/vim-textobj-rubyblock') " Add the concept of a ruby block to vim
call minpac#add('ngmy/vim-rubocop', { 'type': 'opt' })
call minpac#add('posva/vim-vue')
call minpac#add('rking/ag.vim', { 'type': 'opt' })
call minpac#add('scrooloose/nerdtree')                                  " Allow file system display and manipulation
call minpac#add('slim-template/vim-slim')
call minpac#add('tmhedberg/matchit')                                    " Makes extended % matching for HTML, LaTeX, and many other languages
call minpac#add('tpope/vim-abolish')
call minpac#add('tpope/vim-bundler', { 'type': 'opt' })
call minpac#add('tpope/vim-endwise')
call minpac#add('tpope/vim-fugitive')
call minpac#add('tpope/vim-git')
call minpac#add('tpope/vim-rails')
call minpac#add('tpope/vim-rake')
call minpac#add('tpope/vim-rhubarb', { 'type': 'opt' })
call minpac#add('tpope/vim-sleuth', { 'type': 'opt' })
call minpac#add('tpope/vim-surround')
call minpac#add('tpope/vim-unimpaired')
call minpac#add('vim-ruby/vim-ruby')
call minpac#add('vim-scripts/LanguageTool', { 'type': 'opt' })          " Check grammar via :LanguageToolCheck
call minpac#add('vim-scripts/tComment')
call minpac#add('vim-syntastic/syntastic')                                 " Linter / syntax checker

set nobackup
set nowritebackup
set notimeout
set ttimeout
set ttimeoutlen=10
set noswapfile                    " It's 2012, Vim."
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set t_Co=256
syntax on

set spelllang=en
set spellfile=$HOME/.vim/spell/en.utf-8.add

" Fix backspace
set backspace=indent,eol,start
" fixdel " neovim incompatible

" Send more characters for redraws
set ttyfast

" Use Bash as shell
set shell=/usr/local/bin/bash

" Enable mouse use in all modes
set mouse=a
" set ttymouse=xterm2 " neovim incompatible

filetype plugin indent on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

" Display extra whitespace
set list listchars=tab:»·,trail:·
" Clipboard fix for OsX
set clipboard=unnamed

" Numbers
set number
set numberwidth=2

"Folding
set foldmethod=indent
set foldlevelstart=99

" Autocompletion options
set wildmode=list:longest,list:full
set complete=.,w,b,u,t

" When spellcheck is enabled, autocomplete from dictionary
set complete+=kspell

" Tags
let Tlist_Ctags_Cmd = "/usr/bin/env ctags -R --exclude=.git --exclude=log -f ./.tags *"
set tags+=.tags

source $HOME/.vim/autocommands.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/rails.vim
source $HOME/.vim/snippets.vim
source $HOME/.vim/syntax.vim
source $HOME/.vim/testing.vim
source $HOME/.vim/tmux.vim
source $HOME/.vim/visual_fixes.vim
source $HOME/.vim/extras.vim
source $HOME/.vim/markdown.vim
source $HOME/.vim/dash.vim

packloadall
